"""fix_exchange_offers_status

Revision ID: f3b58057b76e
Revises: 5de0825565ab
Create Date: 2026-05-31 20:34:05.691713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b58057b76e'
down_revision: Union[str, Sequence[str], None] = '5de0825565ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_offers', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_offers', 'status')
    # ### end Alembic commands ###
